/* GENERATED by _build/build.mjs — edit _build/data.mjs instead */
window.BLIP = {
 "PRICE": 16,
 "FREE": 30,
 "SET": [
  {
   "n": "Bo",
   "slug": "bo",
   "k": "blue",
   "f": "the dark",
   "g": "night",
   "s": "Bedroom, lights off, door left open exactly the right amount.",
   "t": "#BFE7FF",
   "r": "Common",
   "o": "1 in 4",
   "h": "62 mm"
  },
  {
   "n": "Pim",
   "slug": "pim",
   "k": "lime",
   "f": "being looked at",
   "g": "school",
   "s": "Class assembly, reading out loud, saying your own name to a room.",
   "t": "#DDF5B8",
   "r": "Common",
   "o": "1 in 4",
   "h": "71 mm"
  },
  {
   "n": "Nix",
   "slug": "nix",
   "k": "orange",
   "f": "loud noises",
   "g": "everyday",
   "s": "Hand dryers, fireworks, the vacuum, a balloon about to go.",
   "t": "#FFDDBA",
   "r": "Common",
   "o": "1 in 5",
   "h": "58 mm"
  },
  {
   "n": "Wren",
   "slug": "wren",
   "k": "pink",
   "f": "somewhere new",
   "g": "school",
   "s": "First day, new school, new house, a party where you know nobody.",
   "t": "#FFD3E4",
   "r": "Common",
   "o": "1 in 5",
   "h": "60 mm"
  },
  {
   "n": "Tup",
   "slug": "tup",
   "k": "yellow",
   "f": "being away",
   "g": "away",
   "s": "Sleepovers, hospital stays, the first night in a strange bed.",
   "t": "#FFEFB8",
   "r": "Uncommon",
   "o": "1 in 8",
   "h": "64 mm"
  },
  {
   "n": "Gog",
   "slug": "gog",
   "k": "purple",
   "f": "bad dreams",
   "g": "night",
   "s": "Waking at three in the morning and not shouting for anyone.",
   "t": "#E3D2FF",
   "r": "Rare",
   "o": "1 in 11",
   "h": "54 mm"
  },
  {
   "n": "Pib",
   "slug": "pib",
   "k": "brave",
   "f": "being brave",
   "g": "hospital",
   "s": "Injections, stitches, the dentist, anything with a waiting room.",
   "t": "#FFD9CF",
   "r": "Uncommon",
   "o": "1 in 7",
   "h": "59 mm"
  },
  {
   "n": "Lun",
   "slug": "lun",
   "k": "miss",
   "f": "missing someone",
   "g": "away",
   "s": "Someone who is away for a while, or someone who is not coming back.",
   "t": "#D6E6FF",
   "r": "Rare",
   "o": "1 in 12",
   "h": "78 mm"
  },
  {
   "n": "Fen",
   "slug": "fen",
   "k": "anger",
   "f": "anger",
   "g": "everyday",
   "s": "When it is far too big for your body and comes out at the wrong person.",
   "t": "#FFD0CA",
   "r": "Uncommon",
   "o": "1 in 8",
   "h": "56 mm"
  },
  {
   "n": "Moss",
   "slug": "moss",
   "k": "shy",
   "f": "shyness",
   "g": "school",
   "s": "Parties, playdates, being made to say hello to an adult you do not know.",
   "t": "#CFF2E4",
   "r": "Common",
   "o": "1 in 5",
   "h": "57 mm"
  },
  {
   "n": "Sprig",
   "slug": "sprig",
   "k": "grow",
   "f": "growing up",
   "g": "everyday",
   "s": "Losing a tooth, a bigger bike, moving up a year, being the older one now.",
   "t": "#DCF3C6",
   "r": "Uncommon",
   "o": "1 in 9",
   "h": "61 mm"
  },
  {
   "n": "Vesper",
   "slug": "vesper",
   "k": "night",
   "f": "the 2am worries",
   "g": "night",
   "s": "The big ones about everything at once, that only arrive in the dark.",
   "t": "#D8D2F5",
   "r": "Rare",
   "o": "1 in 14",
   "h": "63 mm"
  }
 ],
 "GROUPS": [
  {
   "id": "all",
   "label": "Everything"
  },
  {
   "id": "night",
   "label": "Night & sleep"
  },
  {
   "id": "school",
   "label": "School & people"
  },
  {
   "id": "hospital",
   "label": "Hospital & hurt"
  },
  {
   "id": "away",
   "label": "Being apart"
  },
  {
   "id": "everyday",
   "label": "Everyday"
  }
 ],
 "BUNDLES": [
  {
   "id": "s0",
   "t": "The night set",
   "p": 42,
   "was": 48,
   "m": [
    0,
    5,
    11
   ],
   "d": "Bo for the dark, Gog for bad dreams and Vesper for the 2am ones. The three that live on a bedside table."
  },
  {
   "id": "s1",
   "t": "The hospital set",
   "p": 42,
   "was": 48,
   "m": [
    6,
    4,
    7
   ],
   "d": "Pib for being brave, Tup for being away and Lun for missing someone. Packed for a stay, not a visit."
  },
  {
   "id": "s2",
   "t": "The new school set",
   "p": 42,
   "was": 48,
   "m": [
    3,
    1,
    9
   ],
   "d": "Wren for somewhere new, Pim for being looked at and Moss for shyness. Posted to land the week before term."
  }
 ]
};
